# Generated by Django 5.1.3 on 2024-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0017_alter_product_sku_alter_store_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name_short",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
