# Generated by Django 5.1.3 on 2024-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0018_product_name_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
    ]
